
# Site settings
title: Jim Taylor | Front-end Developer
name: Jim Taylor
handle: iamjimtaylor
email: me@iamjimtaylor.com
description: "Jim Taylor - I'm a self-motivated, creative and solution focused Senior Web Development Manager from Liverpool"
baseurl: "" 
url: "http://iamjimtaylor.com"

# Build settings
markdown: kramdown
sass:
  style: compressed
