# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jim Taylor
email: me@iamjimtaylor.com
description: Head of Development at Ph. Creative
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iamjimtaylor.com" # the base hostname & protocol for your site
twitter_username: iamjimtaylor
github_username:  iamjimtaylor

# Build settings
markdown: kramdown
