
# Site Settings
title: Jim Taylor | Front-end Developer
name: Jim Taylor
handle: iamjimtaylor
email: me@iamjimtaylor.com
description: "Jim Taylor - I'm a self-motivated, creative and solution focused Senior Web Development Manager from Liverpool"
baseurl: "" 
url: "http://iamjimtaylor.com"

# Build Settings
markdown: kramdown
sass:
  style: compressed

# Main Navigation
header_links:
  - link:
    url: /
    text: Home
    title: Jim Taylor
    blank: false
  - link:
    url: /about/
    text: About
    title: A little bit about myself
    blank: false
  - link:
    url: /posts/
    text: Blog
    title: View blog posts I've written
    blank: false
