
# ----------------------- #
#      Main Configs       #
# ----------------------- #
title: Jim Taylor | Managing Director of Ph.Digital
name: Jim Taylor
handle: iamjimtaylor
email: me@iamjimtaylor.com
description: "Jim Taylor - Managing Director of Ph.Digital at the award winning Employer Brand Agency Ph.Creative."
baseurl: "" 
url: https://iamjimtaylor.com
enforce_ssl: iamjimtaylor.com

navigation:
- text: About
  url: /about/
- text: Blog
  url: /posts/

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
markdown: kramdown
sass:
  style: compressed

gems: 
  - jekyll-sitemap
  - jekyll-paginate

paginate: 12          # gem install jekyll-paginate
paginate_path: "/posts/page:num/"
