
# ----------------------- #
#      Main Configs       #
# ----------------------- #
title: Jim Taylor | Front-end Developer
name: Jim Taylor
handle: iamjimtaylor
email: me@iamjimtaylor.com
description: "Jim Taylor - I'm a self-motivated, creative and solution focused Senior Web Development Manager from Liverpool"
baseurl: "" 
url: "http://iamjimtaylor.com"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
markdown: kramdown
sass:
  style: compressed

gems: 
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5          # gem install jekyll-paginate
paginate_path: "/posts/page:num/"  

