
# Site settings
title: Jim Taylor | Web Developer
name: Jim Taylor
handle: iamjimtaylor
email: me@iamjimtaylor.com
description: Jim Taylor - Head of Web Development at Ph. Creative
baseurl: "" 
url: "http://iamjimtaylor.com"

# Build settings
markdown: kramdown
