
# Site settings
title: Jim Taylor
email: me@iamjimtaylor.com
description: Head of Development at Ph. Creative
baseurl: "" 
url: "http://iamjimtaylor.com" 
twitter_username: iamjimtaylor
github_username:  iamjimtaylor

# Build settings
markdown: kramdown
